apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ecommerce
type: Opaque
data:
  # Database Credentials (base64 encoded)
  POSTGRES_USER: cG9zdGdyZXM=  # postgres
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # password
  MONGODB_USERNAME: bW9uZ29kYg==  # mongodb
  MONGODB_PASSWORD: cGFzc3dvcmQ=  # password
  
  # JWT Secrets
  JWT_SECRET: eW91ci1qd3Qtc2VjcmV0LWtleS1oZXJl  # your-jwt-secret-key-here
  JWT_REFRESH_SECRET: eW91ci1yZWZyZXNoLXNlY3JldC1rZXk=  # your-refresh-secret-key
  
  # API Keys
  STRIPE_SECRET_KEY: c2tfdGVzdF95b3VyX3N0cmlwZV9zZWNyZXRfa2V5  # sk_test_your_stripe_secret_key
  PAYPAL_CLIENT_SECRET: eW91ci1wYXlwYWwtY2xpZW50LXNlY3JldA==  # your-paypal-client-secret
  
  # Email Service
  SMTP_PASSWORD: eW91ci1zbXRwLXBhc3N3b3Jk  # your-smtp-password
  
  # External Services
  AWS_ACCESS_KEY_ID: eW91ci1hd3MtYWNjZXNzLWtleQ==  # your-aws-access-key
  AWS_SECRET_ACCESS_KEY: eW91ci1hd3Mtc2VjcmV0LWtleQ==  # your-aws-secret-key
  
  # Vault Token
  VAULT_TOKEN: eW91ci12YXVsdC10b2tlbg==  # your-vault-token
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: ecommerce
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbSI6eyJ1c2VybmFtZSI6InVzZXIiLCJwYXNzd29yZCI6InBhc3MiLCJhdXRoIjoiZFhObGNqcHdZWE56In19fQ==
