apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: ecommerce
type: Opaque
data:
  # Keycloak Admin Credentials
  KEYCLOAK_ADMIN: YWRtaW4=  # admin
  KEYCLOAK_ADMIN_PASSWORD: YWRtaW4xMjM=  # admin123
  
  # Database Connection
  KC_DB_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtc2VydmljZTo1NDMyL2tleWNsb2Fr  # jdbc:postgresql://postgres-service:5432/keycloak
  KC_DB_USERNAME: a2V5Y2xvYWs=  # keycloak
  KC_DB_PASSWORD: cGFzc3dvcmQ=  # password
  
  # Client Secrets
  ECOMMERCE_CLIENT_SECRET: ZWNvbW1lcmNlLWNsaWVudC1zZWNyZXQ=  # ecommerce-client-secret
  ADMIN_CLIENT_SECRET: YWRtaW4tY2xpZW50LXNlY3JldA==  # admin-client-secret
  
  # SMTP Configuration
  SMTP_HOST: c210cC5nbWFpbC5jb20=  # smtp.gmail.com
  SMTP_PORT: NTg3  # 587
  SMTP_USERNAME: eW91ci1lbWFpbEBnbWFpbC5jb20=  # your-email@gmail.com
  SMTP_PASSWORD: eW91ci1zbXRwLXBhc3N3b3Jk  # your-smtp-password
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: ecommerce
data:
  keycloak.conf: |
    # Database
    db=postgres
    db-url=jdbc:postgresql://postgres-service:5432/keycloak
    db-username=keycloak
    db-password=password
    
    # HTTP
    http-enabled=true
    http-port=8080
    http-host=0.0.0.0
    
    # HTTPS (disabled for development)
    https-port=8443
    
    # Hostname
    hostname=keycloak.ecommerce.local
    hostname-strict=false
    hostname-strict-https=false
    
    # Proxy
    proxy=edge
    
    # Features
    features=token-exchange,admin-fine-grained-authz
    
    # Logging
    log-level=INFO
    log-console-output=default
    
    # Health
    health-enabled=true
    metrics-enabled=true
    
    # Cache
    cache=ispn
    cache-stack=kubernetes
  
  realm-export.json: |
    {
      "realm": "ecommerce",
      "enabled": true,
      "displayName": "E-Commerce Platform",
      "displayNameHtml": "<div class=\"kc-logo-text\"><span>E-Commerce Platform</span></div>",
      "registrationAllowed": true,
      "registrationEmailAsUsername": true,
      "rememberMe": true,
      "verifyEmail": true,
      "loginWithEmailAllowed": true,
      "duplicateEmailsAllowed": false,
      "resetPasswordAllowed": true,
      "editUsernameAllowed": false,
      "bruteForceProtected": true,
      "permanentLockout": false,
      "maxFailureWaitSeconds": 900,
      "minimumQuickLoginWaitSeconds": 60,
      "waitIncrementSeconds": 60,
      "quickLoginCheckMilliSeconds": 1000,
      "maxDeltaTimeSeconds": 43200,
      "failureFactor": 30,
      "defaultRoles": ["default-roles-ecommerce"],
      "requiredCredentials": ["password"],
      "passwordPolicy": "length(8) and digits(1) and lowerCase(1) and upperCase(1) and specialChars(1) and notUsername",
      "otpPolicyType": "totp",
      "otpPolicyAlgorithm": "HmacSHA1",
      "otpPolicyInitialCounter": 0,
      "otpPolicyDigits": 6,
      "otpPolicyLookAheadWindow": 1,
      "otpPolicyPeriod": 30,
      "clients": [
        {
          "clientId": "ecommerce-customer",
          "name": "E-Commerce Customer Platform",
          "enabled": true,
          "clientAuthenticatorType": "client-secret",
          "secret": "ecommerce-client-secret",
          "redirectUris": [
            "http://localhost:3000/*",
            "https://customer.ecommerce.local/*"
          ],
          "webOrigins": [
            "http://localhost:3000",
            "https://customer.ecommerce.local"
          ],
          "protocol": "openid-connect",
          "publicClient": false,
          "bearerOnly": false,
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": true,
          "serviceAccountsEnabled": false,
          "fullScopeAllowed": true,
          "defaultClientScopes": [
            "web-origins",
            "role_list",
            "profile",
            "roles",
            "email"
          ],
          "optionalClientScopes": [
            "address",
            "phone",
            "offline_access",
            "microprofile-jwt"
          ]
        },
        {
          "clientId": "ecommerce-admin",
          "name": "E-Commerce Admin Dashboard",
          "enabled": true,
          "clientAuthenticatorType": "client-secret",
          "secret": "admin-client-secret",
          "redirectUris": [
            "http://localhost:3100/*",
            "https://admin.ecommerce.local/*"
          ],
          "webOrigins": [
            "http://localhost:3100",
            "https://admin.ecommerce.local"
          ],
          "protocol": "openid-connect",
          "publicClient": false,
          "bearerOnly": false,
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": true,
          "serviceAccountsEnabled": true,
          "fullScopeAllowed": true,
          "defaultClientScopes": [
            "web-origins",
            "role_list",
            "profile",
            "roles",
            "email"
          ],
          "optionalClientScopes": [
            "address",
            "phone",
            "offline_access",
            "microprofile-jwt"
          ]
        },
        {
          "clientId": "ecommerce-api",
          "name": "E-Commerce API Gateway",
          "enabled": true,
          "clientAuthenticatorType": "client-secret",
          "secret": "api-client-secret",
          "bearerOnly": true,
          "protocol": "openid-connect",
          "publicClient": false,
          "standardFlowEnabled": false,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": false,
          "serviceAccountsEnabled": true,
          "fullScopeAllowed": true
        }
      ],
      "roles": {
        "realm": [
          {
            "name": "customer",
            "description": "Customer role for e-commerce platform"
          },
          {
            "name": "admin",
            "description": "Administrator role for e-commerce platform"
          },
          {
            "name": "manager",
            "description": "Manager role for e-commerce platform"
          },
          {
            "name": "support",
            "description": "Support role for e-commerce platform"
          }
        ]
      },
      "groups": [
        {
          "name": "customers",
          "path": "/customers",
          "realmRoles": ["customer"]
        },
        {
          "name": "administrators",
          "path": "/administrators",
          "realmRoles": ["admin"]
        },
        {
          "name": "managers",
          "path": "/managers",
          "realmRoles": ["manager"]
        },
        {
          "name": "support-team",
          "path": "/support-team",
          "realmRoles": ["support"]
        }
      ],
      "users": [
        {
          "username": "admin",
          "enabled": true,
          "emailVerified": true,
          "firstName": "System",
          "lastName": "Administrator",
          "email": "admin@ecommerce.local",
          "credentials": [
            {
              "type": "password",
              "value": "admin123",
              "temporary": false
            }
          ],
          "realmRoles": ["admin"],
          "groups": ["/administrators"]
        },
        {
          "username": "customer",
          "enabled": true,
          "emailVerified": true,
          "firstName": "Test",
          "lastName": "Customer",
          "email": "customer@ecommerce.local",
          "credentials": [
            {
              "type": "password",
              "value": "customer123",
              "temporary": false
            }
          ],
          "realmRoles": ["customer"],
          "groups": ["/customers"]
        }
      ],
      "smtpServer": {
        "host": "smtp.gmail.com",
        "port": "587",
        "from": "noreply@ecommerce.local",
        "fromDisplayName": "E-Commerce Platform",
        "replyTo": "support@ecommerce.local",
        "replyToDisplayName": "E-Commerce Support",
        "envelopeFrom": "noreply@ecommerce.local",
        "ssl": "false",
        "starttls": "true",
        "auth": "true",
        "user": "your-email@gmail.com",
        "password": "your-smtp-password"
      },
      "loginTheme": "keycloak",
      "accountTheme": "keycloak",
      "adminTheme": "keycloak",
      "emailTheme": "keycloak",
      "internationalizationEnabled": true,
      "supportedLocales": ["en", "es", "fr", "de"],
      "defaultLocale": "en"
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-themes
  namespace: ecommerce
data:
  custom-theme.css: |
    /* Custom E-Commerce Theme */
    .login-pf body {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    }
    
    .login-pf .container {
      background-color: rgba(255, 255, 255, 0.95);
      border-radius: 10px;
      box-shadow: 0 10px 30px rgba(0, 0, 0, 0.3);
    }
    
    .login-pf-header h1 {
      color: #333;
      font-weight: 300;
    }
    
    .btn-primary {
      background-color: #667eea;
      border-color: #667eea;
    }
    
    .btn-primary:hover {
      background-color: #5a6fd8;
      border-color: #5a6fd8;
    }
    
    .form-control:focus {
      border-color: #667eea;
      box-shadow: 0 0 0 0.2rem rgba(102, 126, 234, 0.25);
    }
    
    .alert-error {
      background-color: #f8d7da;
      border-color: #f5c6cb;
      color: #721c24;
    }
    
    .alert-success {
      background-color: #d4edda;
      border-color: #c3e6cb;
      color: #155724;
    }
