apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: ecommerce
data:
  .env.local: |
    # API Configuration
    NEXT_PUBLIC_API_URL=http://api-gateway:8080
    NEXT_PUBLIC_AUTH_URL=http://auth-service:3001
    NEXT_PUBLIC_ADMIN_API_URL=http://admin-service:3012
    
    # Environment
    NODE_ENV=production
    
    # Features
    NEXT_PUBLIC_ENABLE_ANALYTICS=true
    NEXT_PUBLIC_ENABLE_CHAT=true
    NEXT_PUBLIC_ENABLE_NOTIFICATIONS=true
    
    # CDN
    NEXT_PUBLIC_CDN_URL=https://cdn.ecommerce.local
    
    # Payment
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_example
    
    # Social Login
    NEXT_PUBLIC_GOOGLE_CLIENT_ID=google-client-id
    NEXT_PUBLIC_FACEBOOK_APP_ID=facebook-app-id
