global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3002']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:3003']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:3004']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:3005']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'cart-service'
    static_configs:
      - targets: ['cart-service:3006']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'inventory-service'
    static_configs:
      - targets: ['inventory-service:3007']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'shipping-service'
    static_configs:
      - targets: ['shipping-service:3008']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'promotion-service'
    static_configs:
      - targets: ['promotion-service:3009']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'review-service'
    static_configs:
      - targets: ['review-service:3010']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:3011']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'admin-service'
    static_configs:
      - targets: ['admin-service:3012']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgresql:5432']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    scrape_interval: 30s
