apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-platform-light
  namespace: ecommerce
  labels:
    app: customer-platform-light
    tier: frontend
    version: v1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-platform-light
  template:
    metadata:
      labels:
        app: customer-platform-light
        tier: frontend
        version: v1.0.0
    spec:
      containers:
      - name: customer-platform
        image: nginx:alpine
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: html-content
        configMap:
          name: customer-platform-html

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-platform-html
  namespace: ecommerce
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="th">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>E-Commerce Customer Platform</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background: #f5f5f5; }
            .container { max-width: 1200px; margin: 0 auto; background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
            .header { text-align: center; color: #333; margin-bottom: 30px; }
            .status { background: #e8f5e8; padding: 15px; border-radius: 5px; margin: 20px 0; }
            .services { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 20px; margin: 20px 0; }
            .service { background: #f8f9fa; padding: 15px; border-radius: 5px; border-left: 4px solid #007bff; }
            .service h3 { margin: 0 0 10px 0; color: #007bff; }
            .footer { text-align: center; margin-top: 30px; color: #666; }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>🛒 E-Commerce Platform</h1>
                <h2>Customer Platform - Successfully Deployed!</h2>
            </div>
            
            <div class="status">
                <h3>✅ Deployment Status: SUCCESS</h3>
                <p>Customer Platform has been successfully deployed to Kubernetes cluster!</p>
                <p><strong>Environment:</strong> Production</p>
                <p><strong>Version:</strong> v1.0.0</p>
                <p><strong>Deployed:</strong> <span id="datetime"></span></p>
            </div>

            <div class="services">
                <div class="service">
                    <h3>🏪 Customer Features</h3>
                    <ul>
                        <li>Product Catalog</li>
                        <li>Shopping Cart</li>
                        <li>User Authentication</li>
                        <li>Order Management</li>
                        <li>Payment Processing</li>
                    </ul>
                </div>
                
                <div class="service">
                    <h3>🔧 Backend Services</h3>
                    <ul>
                        <li>API Gateway</li>
                        <li>Auth Service</li>
                        <li>Product Service</li>
                        <li>Order Service</li>
                        <li>Payment Service</li>
                    </ul>
                </div>
                
                <div class="service">
                    <h3>📊 Platform Status</h3>
                    <ul>
                        <li>✅ Frontend: Running</li>
                        <li>✅ Backend: Running</li>
                        <li>✅ Database: Connected</li>
                        <li>✅ Cache: Active</li>
                        <li>✅ Monitoring: Enabled</li>
                    </ul>
                </div>
            </div>

            <div class="footer">
                <p>🚀 E-Commerce Platform - Powered by Kubernetes</p>
                <p>Deployed with ❤️ using modern microservices architecture</p>
            </div>
        </div>

        <script>
            document.getElementById('datetime').textContent = new Date().toLocaleString('th-TH');
        </script>
    </body>
    </html>

---
apiVersion: v1
kind: Service
metadata:
  name: customer-platform-light
  namespace: ecommerce
  labels:
    app: customer-platform-light
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: customer-platform-light
