name: Branch Protection Setup

on:
  workflow_dispatch:
    inputs:
      setup_protection:
        description: 'Setup branch protection rules'
        required: true
        default: 'true'
        type: boolean

jobs:
  setup-branch-protection:
    runs-on: ubuntu-latest
    if: github.event.inputs.setup_protection == 'true'
    
    steps:
      - name: Setup Branch Protection for Main
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            
            // Main branch protection
            await github.rest.repos.updateBranchProtection({
              owner,
              repo,
              branch: 'main',
              required_status_checks: {
                strict: true,
                contexts: [
                  'ci/jenkins/build',
                  'ci/jenkins/test',
                  'ci/jenkins/security-scan'
                ]
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                required_approving_review_count: 2,
                dismiss_stale_reviews: true,
                require_code_owner_reviews: true,
                require_last_push_approval: true
              },
              restrictions: {
                users: [],
                teams: ['devops-team', 'senior-developers']
              },
              allow_force_pushes: false,
              allow_deletions: false,
              block_creations: false
            });

      - name: Setup Branch Protection for Production
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            
            // Production branch protection
            await github.rest.repos.updateBranchProtection({
              owner,
              repo,
              branch: 'production',
              required_status_checks: {
                strict: true,
                contexts: [
                  'ci/jenkins/build',
                  'ci/jenkins/test',
                  'ci/jenkins/security-scan',
                  'ci/jenkins/performance-test'
                ]
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                required_approving_review_count: 2,
                dismiss_stale_reviews: true,
                require_code_owner_reviews: true
              },
              restrictions: {
                users: [],
                teams: ['devops-team']
              },
              allow_force_pushes: false,
              allow_deletions: false
            });

      - name: Setup Branch Protection for Staging
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            
            // Staging branch protection
            await github.rest.repos.updateBranchProtection({
              owner,
              repo,
              branch: 'staging',
              required_status_checks: {
                strict: true,
                contexts: [
                  'ci/jenkins/build',
                  'ci/jenkins/test'
                ]
              },
              enforce_admins: false,
              required_pull_request_reviews: {
                required_approving_review_count: 1,
                dismiss_stale_reviews: true
              },
              allow_force_pushes: false,
              allow_deletions: false
            });
